export const phrasalVerbCards = [
    "Phrasal Verbs ➜ ACCIDENTS & EMERGENCIES.jpg",
    "Phrasal Verbs ➜ AWAY.jpg",
    "Phrasal Verbs ➜ BREAK.jpg",
    "Phrasal Verbs ➜ BRING.jpg",
    "Phrasal Verbs ➜ COME (2).jpg",
    "Phrasal Verbs ➜ COME.jpg",
    "Phrasal Verbs ➜ COMMUNICATION & MEDIA.jpg",
    "Phrasal Verbs ➜ CRIME & LAW.jpg",
    "Phrasal Verbs ➜ EMOTIONS & FEELINGS.jpg",
    "Phrasal Verbs ➜ ENVIRONMENT & CLIMATE.jpg",
    "Phrasal Verbs ➜ FALL.jpg",
    "Phrasal Verbs ➜ FUN & HBBBIES.jpg",
    "Phrasal Verbs ➜ GET.jpg",
    "Phrasal Verbs ➜ GET1.jpg",
    "Phrasal Verbs ➜ GET2.jpg",
    "Phrasal Verbs ➜ GO (2).jpg",
    "Phrasal Verbs ➜ GO.jpg",
    "Phrasal Verbs ➜ HEALTH & ILLNESS.jpg",
    "Phrasal Verbs ➜ LOOK (2).jpg",
    "Phrasal Verbs ➜ LOOK.jpg",
    "Phrasal Verbs ➜ MAKE.jpg",
    "Phrasal Verbs ➜ MONEY & FINANCE.jpg",
    "Phrasal Verbs ➜ PHONING.jpg",
    "Phrasal Verbs ➜ PROBLEMS & SOLUTIONS.jpg",
    "Phrasal Verbs ➜ PULL.jpg",
    "Phrasal Verbs ➜ PUT.jpg",
    "Phrasal Verbs ➜ RUN.jpg",
    "Phrasal Verbs ➜ SET.jpg",
    "Phrasal Verbs ➜ SHOPPING & BUYING.jpg",
    "Phrasal Verbs ➜ SHOPPING.jpg",
    "Phrasal Verbs ➜ SLEEP.jpg",
    "Phrasal Verbs ➜ STUDY & LEARNING.jpg",
    "Phrasal Verbs ➜ TAKE (2).jpg",
    "Phrasal Verbs ➜ TAKE.jpg",
    "Phrasal Verbs ➜ WEATHER & NATURE.jpg",
];
