export const phrasalVerbCards = [
    "Phrasal Verbs ➜ ACCIDENTS & EMERGENCIES.jpg",
    "Phrasal Verbs ➜ AWAY.jpg",
    "Phrasal Verbs ➜ BREAK.jpg",
    "Phrasal Verbs ➜ Break1.jpg",
    "Phrasal Verbs ➜ BRING.jpg",
    "Phrasal Verbs ➜ Call.jpg",
    "Phrasal Verbs ➜ Call1.jpg",
    "Phrasal Verbs ➜ COME.jpg",
    "Phrasal Verbs ➜ COME1.jpg",
    "Phrasal Verbs ➜ Come2.jpg",
    "Phrasal Verbs ➜ Come3.jpg",
    "Phrasal Verbs ➜ Come4.jpg",
    "Phrasal Verbs ➜ COMMUNICATION & MEDIA.jpg",
    "Phrasal Verbs ➜ CRIME & LAW.jpg",
    "Phrasal Verbs ➜ EMOTIONS & FEELINGS.jpg",
    "Phrasal Verbs ➜ ENVIRONMENT & CLIMATE.jpg",
    "Phrasal Verbs ➜ FALL.jpg",
    "Phrasal Verbs ➜ FUN & HOBBIES.jpg",
    "Phrasal Verbs ➜ GET.jpg",
    "Phrasal Verbs ➜ GET1.jpg",
    "Phrasal Verbs ➜ GET2.jpg",
    "Phrasal Verbs ➜ Get3.jpg",
    "Phrasal Verbs ➜ Get4.jpg",
    "Phrasal Verbs ➜ Give.jpg",
    "Phrasal Verbs ➜ Give1.jpg",
    "Phrasal Verbs ➜ GO.jpg",
    "Phrasal Verbs ➜ GO2.jpg",
    "Phrasal Verbs ➜ Go3.jpg",
    "Phrasal Verbs ➜ HEALTH & ILLNESS.jpg",
    "Phrasal Verbs ➜ LOOK.jpg",
    "Phrasal Verbs ➜ LOOK2.jpg",
    "Phrasal Verbs ➜ Look3.jpg",
    "Phrasal Verbs ➜ MAKE.jpg",
    "Phrasal Verbs ➜ Make1.jpg",
    "Phrasal Verbs ➜ MONEY & FINANCE.jpg",
    "Phrasal Verbs ➜ Move.jpg",
    "Phrasal Verbs ➜ Move1.jpg",
    "Phrasal Verbs ➜ PHONING.jpg",
    "Phrasal Verbs ➜ PROBLEMS & SOLUTIONS.jpg",
    "Phrasal Verbs ➜ PULL.jpg",
    "Phrasal Verbs ➜ PUT.jpg",
    "Phrasal Verbs ➜ Put1.jpg",
    "Phrasal Verbs ➜ RUN.jpg",
    "Phrasal Verbs ➜ Run1.jpg",
    "Phrasal Verbs ➜ SET.jpg",
    "Phrasal Verbs ➜ Set1.jpg",
    "Phrasal Verbs ➜ SHOPPING & BUYING.jpg",
    "Phrasal Verbs ➜ SHOPPING.jpg",
    "Phrasal Verbs ➜ SLEEP.jpg",
    "Phrasal Verbs ➜ STUDY & LEARNING.jpg",
    "Phrasal Verbs ➜ TAKE.jpg",
    "Phrasal Verbs ➜ Take1.jpg",
    "Phrasal Verbs ➜ TAKE2.jpg",
    "Phrasal Verbs ➜ Turn.jpg",
    "Phrasal Verbs ➜ Turn1.jpg",
    "Phrasal Verbs ➜ WEATHER & NATURE.jpg",
    "Phrasal Verbs ➜ Work.jpg",
    "Phrasal Verbs ➜ Work1.jpg",
];
